name: diploma_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.19.3
  image_picker: ^0.7.3
  mask_text_input_formatter: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  http: ^0.13.1
  sqflite: ^2.0.0+3
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  chopper: ^3.0.6
  logging: ^0.11.4
  flutter_datetime_picker: ^1.5.0
  json_annotation: ^3.0.1
  path: ^1.6.4
  path_provider: ^2.0.1
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  flutter_pdfview: ^1.0.1
  permission_handler: ^7.1.0
  filesystem_picker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.6
  build_runner: any
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/developer_image.svg
    - assets/images/client_image.svg
    - assets/icons/icon_placeholder.svg
    - assets/icons/checked_box.svg
    - assets/icons/home_active_icon.svg
    - assets/icons/home_inactive_icon.svg
    - assets/icons/burn_active_icon.svg
    - assets/icons/burn_inactive_icon.svg
    - assets/icons/favorites_active_icon.svg
    - assets/icons/favorites_inactive_icon.svg
    - assets/icons/notification_active_icon.svg
    - assets/icons/notification_inactive_icon.svg
    - assets/icons/profile_active_icon.svg
    - assets/icons/profile_inactive_icon.svg
    - assets/icons/search_icon.svg
    - assets/icons/filter_icon.svg
    - assets/images/ux_image.png
    - assets/images/user_avatar.jpg
    - assets/icons/star_icon.svg
    - assets/images/ux_image.svg
    - assets/images/ux_ui_image.png
    - assets/images/pencil.png
    - assets/icons/down_icon.svg
    - assets/icons/heart_icon.svg
    - assets/icons/up_icon.svg
    - assets/icons/sheet_indicator.svg
    - assets/images/no_data_image.svg
    - assets/images/no_data_image.png
    - assets/icons/document_icon.svg
    - assets/icons/calendar_icon.svg
    - assets/icons/pdf_icon.svg
    - assets/icons/close_icon.svg
    - assets/images/check_image.svg
    - assets/icons/check.svg
    - assets/icons/delete_icon.svg
    - assets/icons/archive_icon.svg
    - assets/images/delete_image.png
    - assets/images/archive_image.png
    - assets/icons/edit_pencil_icon.svg
    - assets/icons/heart_inactive_icon.svg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
